fixed portal code validation and agreement consent update
catenax-ng/tx-portal-frontend-registration pull request #31
Opened 2022-12-02 12:12 UTC by nidhigarg-bmw

2022-12-05 04:41 UTC, lavanya-bmw approved these changes
lgtm

2022-12-05 09:34 UTC, evegufy requested changes
@nidhigarg-bmw this PR is towards main, please to to edit and change to dev:
![image](https://user-images.githubusercontent.com/46191613/205603227-b4a4d68d-20fa-412d-9b38-a95745dcc83b.png)

2022-12-06 07:45 UTC, oyo requested changes
slight simplification

2022-12-06 07:45 UTC, oyo commented on src/components/cax-companyRole.tsx
> +
Better write this as
`return (`
`<p className="agreement-text">`
`{ agreement.documentIds.length`
`? <>{/*Line 190-192*/}</>`
`: <span>{agreement.name}</span>`
`})`

2022-12-06 07:58 UTC, evegufy submitted a review, later dismissed

2022-12-08 14:00 UTC, merged