bugfix/pattern city
catenax-ng/tx-portal-frontend-registration pull request #65
Opened 2023-02-05 22:35 UTC by jjeroch

missing scenarios to cover: 
- St. Catharines
- Val-d'Or
- Presqu'ile

2023-02-05 22:36 UTC, jjeroch commented
@nidhigarg-bmw  I updated the pattern to more fit for required city input validations.
Do you have an idea how we get additionally 

- St. Catharines
- Val-d'Or
- Presqu'ile

also covered inside the pattern.

2023-02-06 16:37 UTC, oyo approved these changes

2023-02-06 16:40 UTC, oyo requested changes

2023-02-06 16:40 UTC, oyo commented on src/helpers/utils.ts
> +  cityPattern: /^[A-Za-zÀ-ÿ]{2,20}+(?:[\s-][a-zA-Z]{2,20}+)*$/,
this doesn't look correct. You can test your patterns in the browser easily. in the dev tools console at the prompt write:

`/^[A-Za-zÀ-ÿ]{2,20}+(?:[\s-][a-zA-Z]{2,20}+)*$/.test('Munich')`

or any other city you like to check

2023-02-07 11:29 UTC, jjeroch commented
@oyo  we spoke:
Test values - all should be valid :)

- Toronto
- St. Catharines
- San Fransisco
- Val-d'Or
- Presqu'ile
- Niagara on the Lake
- Niagara-on-the-Lake
- München
- Villes du Québec
- Provence-Alpes-Côte d'Azur
- Île-de-France
- Kópavogur
- Garðabær
- Sauðárkrókur
- Þorlákshöfn
- Munich

2023-02-07 11:52 UTC, oyo approved these changes
sehr schön ;)

2023-02-07 11:52 UTC, merged